package com.bignerdranch.android.timberworkoutlogs.ui.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Machine: ImageVector
    get() {
        if (_Machine != null) {
            return _Machine!!
        }
        _Machine = ImageVector.Builder(
            name = "Machine",
            defaultWidth = 100.dp,
            defaultHeight = 100.dp,
            viewportWidth = 100f,
            viewportHeight = 100f
        ).apply {
            path(fill = SolidColor(Color(0xFF0351AF))) {
                moveTo(45f, 0.9f)
                horizontalLineToRelative(12.3f)
                curveTo(59f, 1f, 59f, 1f, 60f, 2f)
                arcToRelative(74.5f, 74.5f, 0f, isMoreThanHalf = false, isPositiveArc = true, 0f, 7f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(-5f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(2.6f)
                arcToRelative(2058f, 2058f, 0f, isMoreThanHalf = false, isPositiveArc = true, 19.9f, -0.2f)
                lineTo(81f, 16.8f)
                curveTo(84f, 17f, 84f, 17f, 86f, 19f)
                curveToRelative(0.1f, 2.6f, 0.2f, 5f, 0.1f, 7.6f)
                verticalLineToRelative(2.2f)
                lineTo(86f, 34f)
                lineToRelative(2.4f, 0.3f)
                curveTo(91f, 35f, 91f, 35f, 93f, 38f)
                curveToRelative(0.5f, 3.5f, 0.4f, 7f, 0.4f, 10.4f)
                verticalLineToRelative(3f)
                curveToRelative(0f, 6.9f, 0f, 6.9f, -2.1f, 10.2f)
                arcToRelative(11.4f, 11.4f, 0f, isMoreThanHalf = false, isPositiveArc = true, -7.4f, 1.8f)
                horizontalLineToRelative(-2.6f)
                curveToRelative(-2.8f, -0.5f, -3.5f, -1.1f, -5.3f, -3.4f)
                curveToRelative(-0.4f, -2.4f, -0.4f, -2.4f, -0.4f, -5.2f)
                lineTo(75.6f, 39.4f)
                curveToRelative(0.4f, -2.4f, 0.4f, -2.4f, 1.7f, -4.2f)
                curveTo(79f, 34f, 79f, 34f, 82f, 34f)
                lineTo(82f, 21f)
                lineTo(55f, 21f)
                verticalLineToRelative(7f)
                lineToRelative(1.9f, -0.1f)
                horizontalLineToRelative(2.5f)
                lineToRelative(2.4f, -0.2f)
                lineToRelative(2.2f, 0.3f)
                curveToRelative(3.2f, 4.7f, 2.3f, 9.9f, 2.3f, 15.5f)
                arcToRelative(438.5f, 438.5f, 0f, isMoreThanHalf = false, isPositiveArc = false, 0f, 10f)
                lineTo(66.3f, 57f)
                curveToRelative(-0.3f, 3f, -0.3f, 3f, -1.7f, 4.9f)
                curveToRelative(-3f, 2f, -6.1f, 1.3f, -9.6f, 1.1f)
                verticalLineToRelative(2f)
                lineToRelative(3.3f, -0.2f)
                curveToRelative(4f, 0.2f, 5f, 0.4f, 7.7f, 3.2f)
                curveToRelative(0.4f, 2.4f, 0.4f, 2.4f, 0.3f, 5.1f)
                verticalLineToRelative(2.7f)
                curveTo(66f, 78f, 66f, 78f, 65f, 79f)
                horizontalLineToRelative(-5f)
                verticalLineToRelative(4f)
                horizontalLineToRelative(-5f)
                verticalLineToRelative(6f)
                arcToRelative(8.184376E8f, 8.184376E8f, 0f, isMoreThanHalf = false, isPositiveArc = false, 27.6f, -0.6f)
                curveToRelative(4.3f, 0.8f, 5.8f, 2f, 8.4f, 5.6f)
                verticalLineToRelative(5f)
                lineTo(9f, 99f)
                curveToRelative(0f, -5f, 0f, -5f, 2f, -7.8f)
                curveToRelative(3.7f, -2.8f, 5.7f, -2.8f, 10.3f, -2.7f)
                horizontalLineToRelative(2f)
                arcToRelative(389.4f, 389.4f, 0f, isMoreThanHalf = false, isPositiveArc = true, 11f, 0.3f)
                lineTo(45f, 89f)
                verticalLineToRelative(-6f)
                horizontalLineToRelative(-5f)
                verticalLineToRelative(-4f)
                horizontalLineToRelative(-2.4f)
                curveTo(35f, 79f, 35f, 79f, 34f, 78f)
                lineToRelative(-0.3f, -4.9f)
                lineToRelative(-0.1f, -2.7f)
                curveToRelative(0.4f, -2.4f, 0.4f, -2.4f, 2.2f, -4.2f)
                curveToRelative(3.1f, -1.7f, 5.7f, -1.4f, 9.2f, -1.2f)
                verticalLineToRelative(-2f)
                lineToRelative(-3.8f, 0.2f)
                curveToRelative(-2.5f, 0.1f, -3.7f, 0.1f, -5.8f, -1.3f)
                curveToRelative(-2f, -2.8f, -1.8f, -5f, -1.8f, -8.4f)
                verticalLineToRelative(-12f)
                curveToRelative(0.1f, -10.1f, 0.1f, -10.1f, 2.4f, -13.5f)
                curveToRelative(2.2f, -0.3f, 2.2f, -0.3f, 4.6f, -0.2f)
                horizontalLineToRelative(2.5f)
                lineToRelative(1.9f, 0.2f)
                verticalLineToRelative(-7f)
                lineTo(18f, 21f)
                verticalLineToRelative(13f)
                lineToRelative(4f, 1f)
                curveToRelative(3f, 3f, 2.3f, 6f, 2.3f, 10.2f)
                verticalLineToRelative(12.4f)
                curveToRelative(-0.4f, 2.8f, -1f, 3.7f, -3.3f, 5.4f)
                curveToRelative(-2.3f, 0.4f, -2.3f, 0.4f, -5f, 0.4f)
                lineToRelative(-2.5f, 0.1f)
                curveTo(11f, 63f, 11f, 63f, 8.7f, 61.6f)
                curveTo(6f, 57.5f, 6.5f, 53.4f, 6.6f, 48.5f)
                verticalLineToRelative(-2.9f)
                curveToRelative(0f, -8.3f, 0f, -8.3f, 3.4f, -11.6f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(-3.2f)
                lineToRelative(-0.1f, -4.2f)
                verticalLineToRelative(-2f)
                lineTo(14f, 19f)
                curveToRelative(2f, -2f, 2f, -2f, 4.9f, -2.2f)
                horizontalLineToRelative(7.6f)
                arcTo(13371.4f, 13371.4f, 0f, isMoreThanHalf = false, isPositiveArc = true, 45f, 17f)
                verticalLineToRelative(-6f)
                horizontalLineToRelative(-5f)
                lineTo(40f, 6.6f)
                lineTo(39.8f, 4f)
                curveTo(40.1f, 0.4f, 41.8f, 0.9f, 45f, 0.9f)
                close()
                moveTo(49f, 11f)
                verticalLineToRelative(17f)
                horizontalLineToRelative(2f)
                lineTo(51f, 11f)
                horizontalLineToRelative(-2f)
                close()
                moveTo(49f, 63f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(-2f)
                close()
                moveTo(49f, 83f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-6f)
                horizontalLineToRelative(-2f)
                close()
            }
            path(fill = SolidColor(Color(0xFF56A3FE))) {
                moveTo(43.9f, 30.9f)
                horizontalLineToRelative(15f)
                curveTo(61f, 31f, 61f, 31f, 62f, 32f)
                lineToRelative(0.1f, 6f)
                verticalLineToRelative(11.5f)
                lineTo(62f, 59f)
                horizontalLineTo(38f)
                verticalLineTo(41.6f)
                lineToRelative(-0.1f, -3.6f)
                verticalLineToRelative(-3.4f)
                curveToRelative(0.2f, -4.5f, 2f, -3.7f, 6f, -3.7f)
                close()
            }
            path(fill = SolidColor(Color(0xFF509DF8))) {
                moveTo(16f, 92f)
                curveToRelative(2.8f, -0.4f, 2.8f, -0.4f, 6.4f, -0.4f)
                horizontalLineToRelative(2f)
                arcToRelative(614.4f, 614.4f, 0f, isMoreThanHalf = false, isPositiveArc = true, 20.7f, 0f)
                arcToRelative(1426f, 1426f, 0f, isMoreThanHalf = false, isPositiveArc = false, 26.2f, 0f)
                horizontalLineToRelative(9.9f)
                lineToRelative(2.8f, 0.4f)
                lineToRelative(2f, 3f)
                horizontalLineTo(14f)
                lineToRelative(2f, -3f)
                close()
            }
            path(fill = SolidColor(Color(0xFF56A3FE))) {
                moveTo(80f, 38f)
                horizontalLineToRelative(9f)
                verticalLineToRelative(12.8f)
                lineToRelative(0.1f, 2.7f)
                verticalLineToRelative(2.6f)
                curveTo(89f, 58f, 89f, 58f, 88f, 59f)
                horizontalLineToRelative(-8f)
                verticalLineTo(38f)
                close()
                moveTo(11f, 38f)
                horizontalLineToRelative(9f)
                verticalLineToRelative(21f)
                horizontalLineToRelative(-8f)
                curveToRelative(-1f, -1f, -1f, -1f, -1.1f, -3f)
                verticalLineTo(45.2f)
                lineTo(11f, 38f)
                close()
                moveTo(38f, 69f)
                horizontalLineToRelative(24f)
                verticalLineToRelative(6f)
                horizontalLineTo(38f)
                verticalLineToRelative(-6f)
                close()
            }
            path(fill = SolidColor(Color(0xFF519EF9))) {
                moveTo(44f, 5f)
                horizontalLineToRelative(12f)
                verticalLineToRelative(3f)
                horizontalLineTo(44f)
                verticalLineTo(5f)
                close()
            }
        }.build()

        return _Machine!!
    }

@Suppress("ObjectPropertyName")
private var _Machine: ImageVector? = null
