package com.android.timberworkoutlogs.ui.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Cables: ImageVector
    get() {
        if (_Cables != null) {
            return _Cables!!
        }
        _Cables = ImageVector.Builder(
            name = "Cables",
            defaultWidth = 100.dp,
            defaultHeight = 100.dp,
            viewportWidth = 100f,
            viewportHeight = 100f
        ).apply {
            path(fill = SolidColor(Color(0xFF000000))) {
                moveTo(44f, 0f)
                horizontalLineToRelative(12f)
                lineToRelative(1f, 2f)
                horizontalLineToRelative(2.1f)
                lineToRelative(9.6f, 0.2f)
                lineTo(72f, 2.2f)
                curveToRelative(4.7f, 0.1f, 8f, 0.3f, 12.3f, 2.5f)
                curveToRelative(2.8f, 5.4f, 2.2f, 10.7f, 2f, 16.6f)
                lineTo(86.3f, 25f)
                lineToRelative(-0.3f, 9f)
                lineToRelative(-2f, 1f)
                lineToRelative(2.6f, 2.4f)
                lineToRelative(3.3f, 3f)
                lineToRelative(1.7f, 1.6f)
                curveToRelative(5.4f, 4.9f, 5.4f, 4.9f, 5.6f, 8f)
                curveToRelative(-0.2f, 3f, -0.2f, 3f, -2.2f, 5f)
                curveToRelative(-4f, 0.3f, -5.5f, 0.3f, -9f, -2f)
                verticalLineToRelative(37f)
                horizontalLineToRelative(9f)
                curveToRelative(1f, 1f, 1f, 1f, 1f, 10f)
                lineTo(4f, 100f)
                curveToRelative(0f, -9f, 0f, -9f, 1f, -10f)
                horizontalLineToRelative(9f)
                lineTo(14f, 53f)
                lineToRelative(-3f, 2f)
                curveToRelative(-3f, 0.3f, -3f, 0.3f, -6f, 0f)
                curveToRelative(-2f, -2f, -2f, -2f, -2.4f, -4.8f)
                curveToRelative(0.5f, -4f, 1.7f, -5.2f, 4.7f, -7.9f)
                lineToRelative(2.3f, -2.2f)
                curveToRelative(2.1f, -1.8f, 4.2f, -3.5f, 6.4f, -5.1f)
                lineToRelative(-2f, -1f)
                arcToRelative(800.7f, 800.7f, 0f, isMoreThanHalf = false, isPositiveArc = true, -0.4f, -16.3f)
                curveToRelative(-0.2f, -8.7f, -0.2f, -8.7f, 2.2f, -13f)
                curveToRelative(5f, -2.7f, 9.9f, -2.5f, 15.5f, -2.5f)
                arcTo(2.8806802E9f, 2.8806802E9f, 0f, isMoreThanHalf = false, isPositiveArc = false, 43f, 2f)
                lineToRelative(1f, -2f)
                close()
                moveTo(47f, 4f)
                verticalLineToRelative(8f)
                horizontalLineToRelative(6f)
                lineTo(53f, 4f)
                horizontalLineToRelative(-6f)
                close()
                moveTo(19.2f, 8.2f)
                curveToRelative(-1.6f, 2.5f, -1.5f, 4.2f, -1.5f, 7.1f)
                verticalLineToRelative(3.1f)
                lineToRelative(0.1f, 3.3f)
                lineTo(17.8f, 25f)
                lineToRelative(0.2f, 8f)
                lineToRelative(3f, -1f)
                lineTo(21f, 10f)
                lineToRelative(22f, -1f)
                lineTo(43f, 7f)
                arcToRelative(976.7f, 976.7f, 0f, isMoreThanHalf = false, isPositiveArc = false, -19.6f, -0.3f)
                curveToRelative(-2.4f, 0.1f, -2.4f, 0.1f, -4.2f, 1.5f)
                close()
                moveTo(57f, 7f)
                verticalLineToRelative(2f)
                lineToRelative(22f, 1f)
                verticalLineToRelative(22f)
                lineToRelative(3f, 1f)
                lineToRelative(0.2f, -11.3f)
                verticalLineToRelative(-6.3f)
                lineToRelative(0.1f, -3f)
                curveToRelative(-0.1f, -2.4f, -0.1f, -2.4f, -1.5f, -4.2f)
                curveToRelative(-2.4f, -1.6f, -4f, -1.5f, -7f, -1.5f)
                lineTo(71f, 6.7f)
                lineToRelative(-3f, 0.1f)
                horizontalLineToRelative(-3.2f)
                lineTo(57f, 7f)
                close()
                moveTo(24f, 13f)
                lineTo(23f, 32f)
                horizontalLineToRelative(22f)
                verticalLineToRelative(-6f)
                horizontalLineToRelative(3f)
                lineToRelative(0.3f, -4.8f)
                lineToRelative(0.2f, -2.7f)
                curveToRelative(-0.3f, -2.6f, -0.3f, -2.6f, -2.4f, -4.3f)
                curveToRelative(-4.4f, -1.7f, -8.3f, -1.5f, -13f, -1.4f)
                lineTo(24f, 13f)
                close()
                moveTo(52f, 16f)
                curveToRelative(-0.6f, 2.5f, -0.6f, 2.5f, -0.3f, 5.2f)
                lineToRelative(0.1f, 2.7f)
                lineToRelative(0.2f, 2.1f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(22f)
                lineToRelative(-1f, -19f)
                lineToRelative(-9.2f, -0.2f)
                lineTo(64f, 12.8f)
                curveToRelative(-6.5f, -0.2f, -6.5f, -0.2f, -11.9f, 3.2f)
                close()
                moveTo(49f, 30f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-2f)
                horizontalLineToRelative(-2f)
                close()
                moveTo(11f, 45f)
                lineToRelative(-2.3f, 2.2f)
                curveToRelative(-2f, 1.6f, -2f, 1.6f, -1.7f, 3.8f)
                curveToRelative(3.6f, -1.5f, 5.7f, -3.7f, 8.4f, -6.6f)
                curveToRelative(6f, -5.5f, 11f, -5.7f, 19f, -5.5f)
                horizontalLineToRelative(3.8f)
                arcToRelative(564.5f, 564.5f, 0f, isMoreThanHalf = false, isPositiveArc = true, 18f, 0f)
                lineToRelative(9.8f, 0.1f)
                horizontalLineToRelative(3.6f)
                curveToRelative(5.7f, 0.1f, 9.4f, 0.3f, 13.5f, 4.4f)
                lineTo(86f, 47f)
                curveToRelative(3f, 3f, 3f, 3f, 7f, 4f)
                curveToRelative(-1.6f, -4f, -4.3f, -6.3f, -7.5f, -9.2f)
                lineToRelative(-3f, -2.7f)
                curveToRelative(-3.5f, -3f, -5.2f, -3.2f, -9.7f, -3.4f)
                arcToRelative(3.9432598E8f, 3.9432598E8f, 0f, isMoreThanHalf = false, isPositiveArc = true, -26.2f, -0.4f)
                lineTo(35.3f, 35f)
                lineToRelative(-3.6f, -0.1f)
                curveToRelative(-9.4f, 0f, -14.2f, 3.5f, -20.7f, 10f)
                close()
                moveTo(21f, 46f)
                lineTo(23f, 47f)
                lineTo(24f, 90f)
                horizontalLineToRelative(5f)
                lineToRelative(1f, -27f)
                lineToRelative(15f, -1f)
                verticalLineToRelative(-9f)
                horizontalLineToRelative(3f)
                lineTo(48f, 43f)
                lineToRelative(-11.8f, -0.2f)
                lineTo(29.5f, 42.8f)
                lineToRelative(-3f, -0.1f)
                curveToRelative(-2.9f, 0.3f, -3.7f, 1f, -5.5f, 3.3f)
                close()
                moveTo(52f, 43f)
                verticalLineToRelative(10f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(9f)
                lineToRelative(15f, 1f)
                lineToRelative(1f, 27f)
                horizontalLineToRelative(5f)
                verticalLineToRelative(-4f)
                arcToRelative(4099.7f, 4099.7f, 0f, isMoreThanHalf = false, isPositiveArc = true, 0.6f, -29.4f)
                verticalLineToRelative(-5.4f)
                lineToRelative(0.1f, -2.3f)
                curveTo(77f, 47f, 77f, 47f, 79f, 45f)
                curveToRelative(-3.4f, -2.3f, -4.6f, -2.2f, -8.5f, -2.2f)
                lineTo(63.8f, 42.8f)
                lineToRelative(-3.4f, 0.1f)
                lineToRelative(-8.4f, 0.1f)
                close()
                moveTo(19f, 47f)
                arcToRelative(210f, 210f, 0f, isMoreThanHalf = false, isPositiveArc = false, -4f, 5f)
                lineToRelative(2f, 1f)
                lineToRelative(1f, 37f)
                horizontalLineToRelative(2f)
                lineTo(20f, 47f)
                horizontalLineToRelative(-1f)
                close()
                moveTo(80f, 47f)
                verticalLineToRelative(43f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-3.4f)
                arcToRelative(3039.3f, 3039.3f, 0f, isMoreThanHalf = false, isPositiveArc = true, 0.6f, -27.7f)
                curveToRelative(0.2f, -5.7f, 0.2f, -5.7f, 2.4f, -7.9f)
                lineToRelative(-5f, -4f)
                close()
                moveTo(49f, 57f)
                verticalLineToRelative(5f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(-5f)
                horizontalLineToRelative(-2f)
                close()
                moveTo(33f, 66f)
                verticalLineToRelative(5f)
                horizontalLineToRelative(34f)
                verticalLineToRelative(-5f)
                lineTo(33f, 66f)
                close()
                moveTo(33f, 75f)
                verticalLineToRelative(6f)
                horizontalLineToRelative(34f)
                verticalLineToRelative(-6f)
                lineTo(33f, 75f)
                close()
                moveTo(33f, 85f)
                verticalLineToRelative(5f)
                horizontalLineToRelative(34f)
                verticalLineToRelative(-5f)
                lineTo(33f, 85f)
                close()
                moveTo(8f, 94f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(84f)
                verticalLineToRelative(-2f)
                lineTo(8f, 94f)
                close()
            }
        }.build()

        return _Cables!!
    }

@Suppress("ObjectPropertyName")
private var _Cables: ImageVector? = null
